pkgname="schema"
output="internal/schema"
wipe=true
no-tests=true
add-global-variants=false
add-panic-variants=false

[mysql]
dbname="todoapp"
host="localhost"
port=3307
user="root"
pass="example"
sslmode="false"
whitelist=["users", "tweets", "follows", "likes"]