// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Follows string
	Likes   string
	Todos   string
	Tweets  string
	Users   string
}{
	Follows: "follows",
	Likes:   "likes",
	Todos:   "todos",
	Tweets:  "tweets",
	Users:   "users",
}
